// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmcmH_3Jxbc86wpgVSuP5h77j2QeDZ_VM',
    appId: '1:997204013284:web:c4f0fce0a0fa8cf339bcf1',
    messagingSenderId: '997204013284',
    projectId: 'cargo-app-9c5d5',
    authDomain: 'cargo-app-9c5d5.firebaseapp.com',
    storageBucket: 'cargo-app-9c5d5.firebasestorage.app',
    measurementId: 'G-4F4EBXY9MR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDw6bQzYP0JLVOScYNbu19duAIuLRL8A4U',
    appId: '1:997204013284:android:11fc0fcd2ed3665a39bcf1',
    messagingSenderId: '997204013284',
    projectId: 'cargo-app-9c5d5',
    storageBucket: 'cargo-app-9c5d5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCD5d8C1-Kgt4nzKVy7Ci-CdvbbRzG0rAg',
    appId: '1:997204013284:ios:055c43b6fa466c7b39bcf1',
    messagingSenderId: '997204013284',
    projectId: 'cargo-app-9c5d5',
    storageBucket: 'cargo-app-9c5d5.firebasestorage.app',
    iosBundleId: 'com.example.CargoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDw6bQzYP0JLVOScYNbu19duAIuLRL8A4U',
    appId: '1:997204013284:ios:11fc0fcd2ed3665a39bcf1',
    messagingSenderId: '997204013284',
    projectId: 'cargo-app-9c5d5',
    storageBucket: 'cargo-app-9c5d5.firebasestorage.app',
    iosBundleId: 'com.example.cargoApp',
  );
}